version: '3.8'
services:
  app:
    build: .
    container_name: python_nmap_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    volumes:
      - .:/app
    networks:
      - my_custom_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my_custom_network

volumes:
  mongo-data:
  
networks:
  my_custom_network:
    external: true